#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-lemon
Version  : 0.9.1
Release  : 3
URL      : https://rubygems.org/downloads/lemon-0.9.1.gem
Source0  : https://rubygems.org/downloads/lemon-0.9.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: rubygem-lemon-bin
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
# Lemon
[Homepage](http://rubyworks.github.com/lemon) |
[User Guide](http://wiki.github.com/rubyworks/lemon) |
[Development](http://github.com/rubyworks/lemon) |
[Issues](http://github.com/rubyworks/lemon/issues)

%package bin
Summary: bin components for the rubygem-lemon package.
Group: Binaries

%description bin
bin components for the rubygem-lemon package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n lemon-0.9.1
gem spec %{SOURCE0} -l --ruby > rubygem-lemon.gemspec

%build
gem build rubygem-lemon.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
lemon-0.9.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/lemon-0.9.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Kernel/cdesc-Kernel.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Kernel/qua_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Kernel/quaclass-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Kernel/singleton_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/command_parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/option_coverage-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/option_dryrun-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/option_format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/option_loadpath-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/option_namespaces-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/option_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/option_parser-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/option_private-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/option_requires-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/option_verbose-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/option_zealous-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/run-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Base/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Coverage/cdesc-Coverage.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Coverage/command_parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Coverage/command_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Generate/cdesc-Generate.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Generate/command_parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Generate/command_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Generate/generate_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Generate/option_caps-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Generate/option_group-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Generate/setup_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/OBrother/cdesc-OBrother.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/OBrother/command_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/OBrother/show_ascii_art-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Scaffold/append_test-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Scaffold/cdesc-Scaffold.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Scaffold/command_parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Scaffold/dryrun%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Scaffold/generate_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Scaffold/output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Scaffold/setup_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Scaffold/test_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Scaffold/write_test-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Test/cdesc-Test.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Test/command_parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/Test/command_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CLI/cdesc-CLI.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Abstract/cdesc-Abstract.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Abstract/coverage-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Abstract/covered_units-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Abstract/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Abstract/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Abstract/tally-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Abstract/uncovered_cases-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Abstract/uncovered_units-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Abstract/undefined_units-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Compact/cdesc-Compact.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Compact/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Outline/cdesc-Outline.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Outline/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Verbose/cdesc-Verbose.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Verbose/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Verbose/unit_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Yaml/cdesc-Yaml.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/Yaml/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverReports/cdesc-CoverReports.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/cdesc-CoverUnit.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/class_method%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/covered%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/private%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/singleton%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/singleton-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/target-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverUnit/to_str-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/calculate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/canonical-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/canonical_cases-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/cdesc-CoverageAnalyzer.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/covered-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/covered_namespaces-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/covered_unit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/covered_units-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/current-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/filter_units-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/initialize_prerequisites-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/namespaces-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/private%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/public_only%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/reporter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/reporter_find-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/reporter_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/reset%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/reset_suite-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/suite%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/suite-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/system-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/target-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/target_namespaces-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/uncovered-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/uncovered_cases-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/uncovered_system-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/uncovered_units-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/undefined-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/undefined_units-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/CoverageAnalyzer/zealous%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/DSL/Covers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/DSL/TestCase-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/DSL/cdesc-DSL.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/DSL/covers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/DSL/test_case-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/DSL/testcase-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/analyzer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/cdesc-Generator.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/generate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/group-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/grouped_units-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/namespaces-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/private%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/term_case-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/term_class_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/term_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/tests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/units_by_case-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Generator/units_by_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/%2b-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/%2d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/access-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/cdesc-Unit.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/covered%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/covered-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/namespace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/private%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/protected%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/public%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/singleton%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/singleton-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/target-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/Unit/to_str-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/capture-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/capture-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/capture_namespace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/cdesc-Snapshot.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/public_units-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/Snapshot/units-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Method/args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Method/cdesc-Method.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Method/comment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Method/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Method/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Method/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Method/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Method/to_sym-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/cdesc-Scope.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/class_methods-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/comment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/instance_methods-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/parent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/scopes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/target-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/Scope/to_units-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/args_for_node-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/cdesc-SourceParser.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/parse_units-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/parser-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/process-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/scopes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/sexp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/tokenize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/SourceParser/units-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestAdvice/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestAdvice/cdesc-TestAdvice.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestAdvice/initialize_copy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestAdvice/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestAdvice/table-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/After-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/Before-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/Concern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/Context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/Omit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/Setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/Skip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/Teardown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/after-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/before-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/cdesc-DSL.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/concern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/context_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/omit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/skip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/DSL/teardown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/advice-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/cdesc-TestCase.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/domain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/domain_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/evaluate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/label-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/scope-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/skip%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/skip%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/skip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/tags-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/target-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/tests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestCase/validate_settings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClass/DSL/cdesc-DSL.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClass/DSL/context_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClass/cdesc-TestClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClass/type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClass/validate_settings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClassMethod/DSL/cdesc-DSL.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClassMethod/DSL/context_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClassMethod/cdesc-TestClassMethod.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClassMethod/class_method%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClassMethod/context.target;/cdesc-context.target;.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClassMethod/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClassMethod/target_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClassMethod/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClassMethod/type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestClassMethod/unit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/DSL/Context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/DSL/Test-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/DSL/cdesc-DSL.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/DSL/context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/DSL/context_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/DSL/test-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/cdesc-TestMethod.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/class_method%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/raise_pending-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/target_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/tested-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/unit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestMethod/validate_settings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/DSL/ClassMethod-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/DSL/ClassUnit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/DSL/Method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/DSL/Unit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/DSL/cdesc-DSL.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/DSL/class_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/DSL/class_unit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/DSL/context_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/DSL/method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/DSL/unit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/cdesc-TestModule.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestModule/validate_settings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/arguments-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/cdesc-TestProc.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/label-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/match%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/procedure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/scope-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/skip%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/skip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/tags-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/target-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/tested-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/to_proc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestProc/topic-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestScope/cdesc-TestScope.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestScope/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestSetup/cdesc-TestSetup.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestSetup/context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestSetup/description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestSetup/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestSetup/run_setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestSetup/run_teardown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestSetup/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestSetup/teardown%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestSetup/teardown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/TestSetup/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/World/cdesc-World.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/cdesc-Lemon.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/cli-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/const_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/ignore_callers-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/metadata-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Lemon/setup_ignore_callers-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Module/cdesc-Module.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/Module/namespace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/lib/lemon/cli/page-lemon_ascii.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/page-HISTORY_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/page-LICENSE_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/lemon-0.9.1/ri/page-SPECSHEET_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/.ruby
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/Config.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/HISTORY.md
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/SPECSHEET.md
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/bin/lemons
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon.yml
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/ae.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/cli.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/cli/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/cli/coverage.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/cli/generate.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/cli/lemon.ascii
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/cli/obrother.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/cli/scaffold.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/cli/test.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/core_ext.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/core_ext/kernel.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/core_ext/module.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/coverage/analyzer.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/coverage/cover_unit.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/coverage/formats/abstract.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/coverage/formats/compact.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/coverage/formats/outline.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/coverage/formats/verbose.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/coverage/formats/yaml.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/coverage/generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/coverage/snapshot.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/coverage/source_parser.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/ignore_callers.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/test_advice.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/test_case.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/test_class.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/test_class_method.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/test_method.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/test_module.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/test_proc.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/test_scope.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/test_setup.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/lib/lemon/test_world.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/spec/applique/ae.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/spec/applique/fs.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/spec/coverage/01_complete.md
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/spec/coverage/02_incomplete.md
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/spec/coverage/03_extensions.md
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/spec/coverage/applique/lemon.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/try/.test
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/try/case_error.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/try/case_fail.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/try/case_pass.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/try/case_pending.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/try/case_scope.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/try/case_singleton.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/try/case_untested.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/try/fixtures/calculator.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/try/fixtures/example-use.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/try/fixtures/example.rb
/usr/lib64/ruby/gems/2.2.0/gems/lemon-0.9.1/try/helpers/loadpath.rb
/usr/lib64/ruby/gems/2.2.0/specifications/lemon-0.9.1.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/lemons
